name: PR File Changes

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  changed-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get changed files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          CHANGED_FILES=$(gh pr view ${{ github.event.pull_request.number }} --json files --jq '.files[].path')
          echo "Changed files:"
          echo "$CHANGED_FILES"

          echo "Fetching content of changed files..."
          for FILE in $CHANGED_FILES; do
            echo "-----------------------"
            echo "File: $FILE"
            echo "Content:"
            cat "$FILE" || echo "File not found (possibly deleted or renamed)"
            echo "-----------------------"
          done