name: PR File Changes

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write

jobs:
  changed-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          CHANGED_FILES=$(gh pr view ${{ github.event.pull_request.number }} --json files --jq '.files[].path')
          echo "Changed files: $CHANGED_FILES"
          echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
          echo "$CHANGED_FILES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Analyze and comment per file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          API_URL="https://60dc-41-83-7-60.ngrok-free.app/analyze/code"

          for FILE in $CHANGED_FILES; do
            if [ -f "$FILE" ]; then
              echo "Processing file: $FILE"

              FILE_CONTENT=$(cat "$FILE" | jq -Rs .)
              JSON_PAYLOAD="{\"code\": $FILE_CONTENT, \"filename\": \"$FILE\"}"

              echo "Sending request to analyzer for $FILE..."
              RESPONSE=$(curl -s -X POST "$API_URL" \
                -H "Content-Type: application/json" \
                -d "$JSON_PAYLOAD")

              echo "Analyzer Response for $FILE:"
              echo "$RESPONSE"

              COMMENT_BODY="### Code Review for \`$FILE\`\n\n\`\`\`json\n$RESPONSE\n\`\`\`"

              # Post comment directly using GitHub CLI
              gh pr comment ${{ github.event.pull_request.number }} --body "$COMMENT_BODY"
            fi
          done
