name: PR File Changes

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  changed-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: List changed files
        run: |
          CHANGED_FILES=$(jq -r '.pull_request.changed_files' $GITHUB_EVENT_PATH)
          echo "Changed files: $CHANGED_FILES"
